from fastapi import APIRouter, Body
from fastapi.responses import StreamingResponse
from ..models import ExportPayload
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import io
import base64
from datetime import datetime

router = APIRouter()


def _draw_base64_image(c: canvas.Canvas, data_url: str, x: int, y: int, w: int):
    if not data_url:
        return
    if "," in data_url:
        header, b64data = data_url.split(",", 1)
    else:
        b64data = data_url
    img_bytes = base64.b64decode(b64data)
    img = ImageReader(io.BytesIO(img_bytes))
    iw, ih = img.getSize()
    aspect = ih / iw if iw else 1.0
    c.drawImage(img, x, y, width=w, height=w * aspect, preserveAspectRatio=True, mask='auto')


@router.post("/api/export/pdf")
async def export_pdf(payload: ExportPayload = Body(...)):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    margin = 36
    cursor_y = height - margin

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, cursor_y, "Beam Analysis Report")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - margin, cursor_y, datetime.now().strftime("%Y-%m-%d %H:%M"))
    cursor_y -= 24

    # Inputs
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, cursor_y, "Inputs")
    cursor_y -= 14
    c.setFont("Helvetica", 10)
    p = payload
    lines = [
        f"Length: {p.params.length} m",
        f"Section: {p.params.section.type}",
        f"Material: {p.params.material.name} (E={p.params.material.E/1e9:.1f} GPa)",
        f"Loads: {len(p.loads)} entries",
    ]
    for line in lines:
        c.drawString(margin, cursor_y, line)
        cursor_y -= 12

    cursor_y -= 6
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, cursor_y, "Plots")
    cursor_y -= 12

    # Add charts
    chart_width = width - 2 * margin
    for img in [p.images.shear, p.images.moment, p.images.deflection]:
        if cursor_y < 200:
            c.showPage()
            cursor_y = height - margin
        _draw_base64_image(c, img or "", margin, cursor_y - 180, chart_width)
        cursor_y -= 200

    # 3D snapshot
    if p.images.snapshot3d:
        if cursor_y < 220:
            c.showPage()
            cursor_y = height - margin
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, cursor_y, "3D View")
        cursor_y -= 12
        _draw_base64_image(c, p.images.snapshot3d, margin, cursor_y - 200, chart_width)
        cursor_y -= 220

    # Footer
    c.setFont("Helvetica", 9)
    c.drawString(margin, 20, "Generated by BeamLab")
    c.save()
    buffer.seek(0)
    return StreamingResponse(buffer, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=beam_report.pdf"})

